
extends Node

var abilitydict = {
attack = {
name = 'Attack',
code = 'attack',
iconnorm = load("res://files/buttons/abils/Attack.png"),
iconpressed = load("res://files/buttons/abils/Attack2.png"),
learnable = false,
description = 'Attempts to attack chosen enemy.',
usetext = '$name goes for straight hit. ',
target = 'enemy',
effect = null,
can_miss = true,
power = 1,
cooldown = 0,
type = 'physical',
price = 0,
costenergy = 0,
costmana = 0,
costother = '',
attributes = ['damage'],
reqs = {level = 0}
},
"pass" : {
name = 'Pass',
code = 'pass',
learnable = false,
description = 'Do nothing.',
usetext = '$name does nothing. ',
target = 'self',
effect = null,
can_miss = false,
power = 0,
cooldown = 0,
type = 'physical',
price = 0,
costenergy = 0,
costmana = 0,
costother = '',
attributes = [],
reqs = {level = 0}
},
escape = {
name = 'Escape',
code = 'escape',
iconnorm = load("res://files/buttons/abils/Escape.png"),
iconpressed = load("res://files/buttons/abils/Escape2.png"),
learnable = false,
description = 'Attempts to escape from the fight.',
usetext = '$name tries to escape from the fight. ',
target = 'self',
effect = null,
can_miss = false,
power = 1,
cooldown = 4,
type = 'physical',
price = 0,
costenergy = 10,
costmana = 0,
costother = '',
attributes = [],
reqs = {level = 0}
},
debilitate = {
name = 'Debilitate',
code = 'debilitate',
iconnorm = load("res://files/buttons/abils/Debiliate.png"),
iconpressed = load("res://files/buttons/abils/Debiliate2.png"),
learnable = true,
description = 'Light attack aimed to slow enemy down.',
usetext = '$name goes for swift, maiming strike. ',
target = 'enemy',
effect = 'debilitateeffect',
can_miss = true,
power = 0.65,
cooldown = 2,
type = 'physical',
price = 100,
costenergy = 3,
costmana = 0,
costother = '',
attributes = ['damage', 'debuff'],
reqs = {'level' : 1, 'stats.agi_cur' : 1}
},
protect = {
name = 'Protect',
code = 'protect',
iconnorm = load("res://files/buttons/abils/Protect.png"),
iconpressed = load("res://files/buttons/abils/Protect2.png"),
learnable = false,
description = 'Shields target ally from incoming attacks. Takes less physical and energy damage from attacks. ',
usetext = '$name moves in to protect $targetname. ',
target = 'ally',
effect = null,
can_miss = true,
power = 1,
cooldown = 0,
type = 'physical',
price = 0,
costenergy = 0,
costmana = 0,
costother = '',
attributes = [],
reqs = {level = 0}
},
heal = {
name = 'Heal',
code = 'heal',
iconnorm = load("res://files/buttons/abils/Heal.png"),
iconpressed = load("res://files/buttons/abils/Heal2.png"),
learnable = true,
requiredspell = 'heal',
description = 'Restores some health to the target. Requires mana to use. ',
usetext = '$name supports $targetname with healing spell. ',
target = 'ally',
effect = null,
can_miss = false,
power = 1,
cooldown = 3,
type = 'spell',
price = 100,
costenergy = 0,
costmana = 10,
costother = '',
attributes = [],
reqs = {'level' : 1, 'stats.maf_cur' : 1}
},
sedation = {
name = 'Sedation',
code = 'sedation',
iconnorm = load("res://files/buttons/abils/Sedation.png"),
iconpressed = load("res://files/buttons/abils/Sedation2.png"),
learnable = true,
requiredspell = 'sedation',
description = "Slows target's reaction, lowering it's speed. ",
usetext = '$name casts Sedation onto $targetname. ',
target = 'enemy',
effect = 'sedationeffect',
can_miss = true,
power = 1,
cooldown = 5,
type = 'spell',
price = 150,
costenergy = 0,
costmana = 10,
costother = '',
attributes = [],
reqs = {'level' : 2, 'stats.maf_cur' : 1}
},
barrier = {
name = 'Barrier',
code = 'barrier',
iconnorm = load("res://files/buttons/abils/Barrier.png"),
iconpressed = load("res://files/buttons/abils/Barrier2.png"),
learnable = true,
requiredspell = 'barrier',
description = "Creates a magical barrier around target, raising it's armor. ",
usetext = '$name casts Barrier onto $targetname. ',
target = 'ally',
effect = 'barriereffect',
can_miss = false,
power = 1,
cooldown = 4,
type = 'spell',
price = 150,
costenergy = 0,
costmana = 12,
costother = '',
attributes = ['buff'],
reqs = {'level' : 2, 'stats.maf_cur' : 2}
},
shackle = {
name = 'Shackle',
code = 'shackle',
learnable = true,
requiredspell = 'shackle',
description = "Ties single target to ground making escape impossible. ",
usetext = '$name casts Shackle onto $targetname. ',
target = 'enemy',
effect = 'shackleeffect',
can_miss = false,
power = 0,
cooldown = 5,
type = 'spell',
price = 150,
costenergy = 0,
costmana = 10,
costother = '',
attributes = ['debuff'],
reqs = {'level' : 3, 'stats.maf_cur' : 2}
},
acidspit = {
name = 'Acid Spit',
code = 'acidspit',
learnable = true,
description = "Deals damage to single target enemy and recudes it's armor. Effect grows with Magic Affinity. ",
usetext = '$name [color=aqua]Spits Acid[/color] at $targetname. ',
target = 'enemy',
effect = 'acidspiteffect',
can_miss = true,
power = 5,
cooldown = 4,
type = 'spell',
price = 200,
costenergy = 0,
costmana = 5,
costother = '',
attributes = ['damage','debuff'],
reqs = {'level' : 4, 'stats.maf_cur' : 4}
},
heavystike = {
name = 'Heavy Strike',
code = 'heavystike',
iconnorm = load("res://files/buttons/abils/Heavy Strike.png"),
iconpressed = load("res://files/buttons/abils/Heavy Strike2.png"),
learnable = true,
description = "A slow, yet powerful attack. ",
usetext = '$name goes for a powerful swing at $targetname. ',
target = 'enemy',
effect = null,
can_miss = true,
power = 1.75,
cooldown = 3,
type = 'physical',
price = 250,
costenergy = 0,
costmana = 0,
costother = '',
attributes = ['damage'],
reqs = {'level' : 3, 'stats.str_cur' : 2}
},
aimedstrike = {
name = 'Aimed Strike',
code = 'aimedstrike',
iconnorm = load("res://files/buttons/abils/Aimed strike.png"),
iconpressed = load("res://files/buttons/abils/Aimed strike2.png"),
learnable = true,
description = "Powerful, quick strike ignoring target's armor. ",
usetext = '$name goes for an Aimed Strike at $targetname. ',
target = 'enemy',
effect = null,
can_miss = true,
power = 1.5,
cooldown = 4,
type = 'physical',
price = 250,
costenergy = 0,
costmana = 0,
costother = '',
attributes = ['damage','physpen'],
reqs = {'level' : 2, 'stats.agi_cur' : 2}
},
leechingstrike = {
name = 'Leeching Strike',
code = 'leechingstrike',
iconnorm = load("res://files/buttons/abils/Lich strike.png"),
iconpressed = load("res://files/buttons/abils/Lich strike2.png"),
learnable = true,
description = "Mana infused attack which restores health based on dealt damage. ",
usetext = '$name launches Leeching Strike at $targetname. ',
target = 'enemy',
effect = null,
can_miss = true,
power = 1.2,
cooldown = 5,
type = 'physical',
price = 300,
costenergy = 0,
costmana = 0,
costother = '',
attributes = ['damage', 'lifesteal'],
reqs = {'level' : 4, 'stats.agi_cur' : 3, 'stats.maf_cur' : 2}
},
mindread = {
name = 'Mind reading',
code = 'mindread',
learnable = true,
requiredspell = 'mindread',
description = "A faster, combat oriented appliance of Mind Reading, allows you to get more information from your enemies. ",
usetext = '$name cast Mind reading onto self. ',
target = 'self',
effect = 'mindreadeffect',
can_miss = false,
power = 0,
cooldown = 0,
type = 'physical',
price = 100,
costenergy = 0,
costmana = 5,
costother = '',
attributes = ['buff', 'onlyself'],
reqs = {}
},
aoeattack = {
name = 'Slam',
code = 'aoeattack',
iconnorm = load("res://files/buttons/abils/Attack.png"),
iconpressed = load("res://files/buttons/abils/Attack2.png"),
learnable = false,
description = 'Attempts to attack chosen enemy.',
usetext = '$name performs [color=aqua]Slam attack[/color]. ',
target = 'enemy',
effect = null,
can_miss = false,
power = 0.8,
cooldown = 4,
type = 'physical',
price = 0,
costenergy = 0,
costmana = 0,
costother = '',
attributes = ['damage','allparty'],
reqs = {level = 0}
},
}

var effects = {
healeffect = {
duration = 0,
effect = 'restorehealth',
type = 'buff',
},
sedationeffect = {
duration = 3,
name = 'Sedation',
code = 'sedationeffect',
type = 'debuff',
stats = [['speed', '-(3+,caster.magic,)']],
},
barriereffect = {
duration = 3,
name = 'Barrier',
code = 'barriereffect',
type = 'buff',
stats = [['armor', '3+,caster.magic,*2']],
},
debilitateeffect = {
duration = 3,
name = 'Debilitate',
code = 'debilitateeffect',
type = 'debuff',
stats = [['speed', '-(2+,caster.power,/2)']],
},
mindreadeffect = {
duration = 5,
name = 'Mind Reading',
code = 'mindreadeffect',
type = 'buff',
stats = [],
},
shackleeffect = {
duration = 6,
name = "Shackled",
code = 'shackleeffect',
type = 'debuff',
stats = [],
},
acidspiteffect = {
duration = 5,
name = "Acid",
code = 'acidspiteffect',
type = 'debuff',
stats = [['armor', '-(3+,caster.magic,)']],
},
}
func restorehealth(caster, target):
	var text = ''
	var value = 25 + (caster.magic*5)
	target.health = min(target.health + value, target.healthmax)
	text = '$name restores ' + str(value) + ' health.'
	return text




