extends Node


var enemygrouppools = {
wolveseasy = { units = [['wolf',2,3]], awareness = 6, captured = null, special = null,
description = 'You come across a small pack of wolves.',
descriptionambush = 'You are attacked by a small pack of wolves.',
},
direwolveseasy = { units = [['direwolf',2,5]], awareness = 18, captured = null, special = null,
description = 'You come across a pack of dangerous dire wolves.',
descriptionambush = 'You are attacked by a pack of dangerous dire wolves.',
},
wolveshard = { units = [['wolf',3,6]], awareness = 15, captured = null, special = null,
description = 'You come across a large pack of wolves.',
descriptionambush = 'You are attacked by a large pack of wolves.',
},
solobear = { units = [['bear',1,1]], awareness = 6, captured = null, special = null,
description = "$scoutname spots a brown bear several yards away, just in time to let you react to him. ",
descriptionambush =  "As you walk through the wildreness, you hear fierce roar. It seems you provoked a bear by getting into it's territory. It breaks out of the woodwork and goes for an attack.",
},
plantseasy = { units = [['plant',2,3]], awareness = 0, captured = null, special = null,
description = 'You come across a bunch of hostile, animated plants. ',
},
fewcougars = { units = [['cougar',2,3]], awareness = 10, captured = null, special = null,
description = "$scoutname spots a group of mountain cougars searching for prey. ",
descriptionambush =  "You are being attacked by a group of mountain cougars!",
},
solospider = { units = [['spider',1,1]], awareness = 12, captured = null, special = null,
description = "$scoutname spots a giant spider hiding in the shadows. ",
descriptionambush =  "A horse-sized spider has detected you trespassing its domain and jumps out to attack.",
},
spidergroup = { units = [['spider',3,4]], awareness = 24, captured = null, special = null,
description = "$scoutname spots a group of giant spiders hiding in the shadows. ",
descriptionambush =  "You are attacked by a group of giant spiders.",
},
oozesgroup = { units = [['ooze',2,3]], awareness = 0, captured = null, special = null,
description = "You come across group of ooze monsters. ",
},
banditseasy = {units = [['bandit',2,3]], awareness = 6, captured = null, special = null,
description = 'You spot a small group of stray bandits. They seem to be unaware of your presence as of yet. ',
descriptionambush = 'You are attacked by a small group of stray bandits. ',
},
thugseasy = {units = [['bandit',2,2]], awareness = 0, captured = ['thugvictim'], special = null,
description = 'You come across a pair of thugs bullying a bystrander. They are busy right now, so you could pass them by unnoticed... ',
},
banditsmedium = {units = [['banditleader', 0,1],['bandit',3,6]], awareness = 12, captured = null, special = null,
description = 'You spot a medium-sized group of stray bandits. They seem to be unaware of your presence as of yet. ',
descriptionambush = 'You are attacked by a group of stray bandits. ',
},
banditshard = {units = [['banditleader', 1,1],['bandit',7,8]], awareness = 15, captured = null, special = null,
description = 'You spot a large group of stray bandits. They seem to be unaware of your presence as of yet. ',
descriptionambush = 'You are attacked by a large group of stray bandits. ',
},
CaliBossSlaver = {units = [['slaver',1,1]], awareness = 0, captured = null, special = null,
description = 'You spot a small group of stray bandits. They seem to be unaware of your presence as of yet. ',
descriptionambush = 'You are attacked by a small group of stray bandits. ',
},
CaliStrayBandit = {units = [['bandit',1,1]], awareness = 0, captured = null, special = null,
description = 'You spot a small group of stray bandits. They seem to be unaware of your presence as of yet. ',
descriptionambush = 'You are attacked by a small group of stray bandits. ',
},
banditcamp = {units = [['bandit',6,8],['banditleader', 1,2]], awareness = 0, captured = ['banditcampcaptured', 'banditcampcaptured'], special = null,
description = 'You come across a bandit encampment. You can spot numerous watchmen moving around and few captives too, which are likely to be sold for slaves soon. ',
},
elfguards = {units = [['elfguard',2,3]], awareness = 15, captured = null, special = null,
description = "You spot a local patrol of elven warriors scouting the surroundings. Surely, they won't be happy with trespassers as this is tribal elven territory. ",
descriptionambush = 'You are attacked by a small group of elven warriors. ',
},
fairy = {units = [['fairy',1,1]], awareness = 0, captured = null, special = null,
description = 'You spot a lone [color=aqua]wild fairy $child[/color] floating through the woods. ',
},
fairyfew = {units = [['fairy',2,4]], awareness = 0, captured = null, special = null, escape = 7,
description = 'You spot a [color=aqua]small group of wild fairies[/color] playing around. ',
descriptionescape = "A group of wild fairies escapes from you before you get close to them. ",
},
dryad = {units = [['dryad',1,1]], awareness = 0, captured = null, special = null,
description = 'You spot a wild [color=aqua]$race $child[/color] walking through the woods.',
},
monstergirl = {units = [['monstergirl',1,1]], awareness = 0, captured = null, special = null, escape = 6,
description =  "You come across a rare $race monster $child. $He hasn't spotted you yet. ",
descriptionescape = "A wild $race escapes from you before you get close to $him. ",
},
monstergirlfew = {units = [['monstergirl',2,4]], awareness = 0, captured = null, special = null, escape = 12,
description =  "You spot a [color=aqua]small group of wild $race[/color] playing around.  ",
descriptionescape = "A group of wild  escapes from you before you get close to them. ",
},
harpy = {units = [['harpy',1,1]], awareness = 0, captured = null, special = null,
description =  "You come across a $race monster $child. $He hasn't spotted you yet. ",
},
slaverseasy = {units = [['slaver',2,3]], awareness = 0, captured = ['slavervictim'], special = null,
description = "You spot a group of $unitnumber slavers leading a sole victim. You can't make out any more details without getting closer.",
},
slaversmedium = {units = [['slaver',3,5]], awareness = 0, captured = ['slavervictim', 'slavervictim'], special = null,
description = "You spot a group of $unitnumber slavers leading few recently captured victims. You can't say much about them without getting closer.",
},
peasant = {units = [['peasant',1,1]], awareness = 0, captured = null, special = null,
description = "You meet a lone [color=aqua]$race $child[/color], native to these lands. $He seems to be unaware of your presence as of yet. ",
},
peasantgroup = {units = [['peasant',2,3]], awareness = 0, captured = null, special = null,
description = "You meet a group of $unitnumber strangers, native to these lands. They seem to be unaware of your presence as of yet. ",
},
travelersgroup = {units = [['traveller',2,3]], awareness = 0, captured = null, special = null,
description = "You meet a group of $unitnumber travellers moving by on the road. They seem to be unaware of your presence as of yet. ",
},
troglodytesmall = {units = [['troglodyte',3,5]], awareness = 20, captured = null, special = null,
description = 'You spot a small group of troglodytes. They seem to be unaware of your presence as of yet. ',
descriptionambush = 'You are attacked by a small group of troglodytes. ',
},
troglodytelarge = {units = [['troglodyte',7,10]], awareness = 16, captured = null, special = null,
description = 'You spot a large group of troglodytes. They seem to be unaware of your presence as of yet. ',
descriptionambush = 'You are attacked by a large group of troglodytes. ',
},
mutant = {units = [['mutant',1,1]], awareness = 25, captured = null, special = null,
description = 'You spot and ugly creature, deformed by magical energy.',
descriptionambush = 'You are attacked by a mutant. ',
},
gembeetle = {
units = [['gembeetle',1,1]], awareness = 0, captured = null, special = null,
description = "You spot an unusual creature. A shiny, multicolored bug of significant size. ",
},
bossgolem = {
units = [['bossgolem',1,1]], awareness = 0, captured = null, special = null,
description = "Golem Boss",
},
bosswyvern = {
units = [['bosswyvern',1,1]], awareness = 0, captured = null, special = null,
description = "Wyvern Boss",
},
tishaquestenemy = {units = [['banditleader',1,1],['bandit',3,3]], awareness = 0, captured = null, special = null,
description = "You meet a group of $unitnumber travellers moving by on the road. They seem to be unaware of your presence as of yet. ",
},
ivranquestenemy = {units = [['ivran',1,1],['elfguard',4,4]], awareness = 0, captured = null, special = null,
description = "You meet a group of $unitnumber travellers moving by on the road. They seem to be unaware of your presence as of yet. ",
},
ayneris1 = {units = [['ayneris',1,1],['elfguard',3,3]], awareness = 0, captured = null, special = null,
description = "You meet a group of $unitnumber travellers moving by on the road. They seem to be unaware of your presence as of yet. ",
},
ayneris2 = {units = [['ayneris',1,1],['elfguard',7,7]], awareness = 0, captured = null, special = null,
description = "You meet a group of $unitnumber travellers moving by on the road. They seem to be unaware of your presence as of yet. ",
},
frostforddryadquest = {units = [['direwolf',6,6],['plant',4,4]], awareness = 0, captured = null, special = null,
description = "You meet a group of $unitnumber travellers moving by on the road. They seem to be unaware of your presence as of yet. ",
},
frostfordzoequest = {units = [['marauder',9,9]], awareness = 0, captured = null, special = null,
description = "You meet a group of $unitnumber travellers moving by on the road. They seem to be unaware of your presence as of yet. ",
},


wimbornguards = {units = [['wimbornpatrol',3,4]], awareness = 0, captured = null, special = null,
description = "You have been spotted by patrolling militia group from Wimborn. ",
},
wimbornguardsmany = {units = [['wimbornpatrol',7,10]], awareness = 0, captured = null, special = null,
description = "You have been spotted by large patrolling militia group from Wimborn. ",
},
gornguards = {units = [['gornpatrol',3,4]], awareness = 0, captured = null, special = null,
description = "You have been spotted by patrolling militia group from Gorn. ",
},
gornguardsmany = {units = [['gornnpatrol',7,10]], awareness = 0, captured = null, special = null,
description = "You have been spotted by large patrolling militia group from Gorn. ",
},
frostfordguards = {units = [['frostfordpatrol',3,4]], awareness = 0, captured = null, special = null,
description = "You have been spotted by patrolling militia group from Frostford. ",
},
frostfordguardsmany = {units = [['frostfordpatrol',7,10]], awareness = 0, captured = null, special = null,
description = "You have been spotted by large patrolling militia group from Frostford. ",
},
amberguardguards = {units = [['amberguardpatrol',3,4]], awareness = 0, captured = null, special = null,
description = "You have been spotted by patrolling militia group from Amberguard. ",
},
amberguardguardsmany = {units = [['amberguardpatrol',7,10]], awareness = 0, captured = null, special = null,
description = "You have been spotted by large patrolling militia group from Amberguard. ",
},
}

var capturespool = {
thugvictim = {
race = ['area'],
originspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 6},{value = 'slave', weight = 12}],
agepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 2}],
sex = ['any'],
faction = 'stranger',
},
slavervictim = {
race = ['area'],
originspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 5},{value = 'poor', weight = 5},{value = 'slave', weight = 12}],
agepool = [['child',20],['teen',60], ['adult', 100]],
sex = ['any'],
faction = 'stranger',
},
banditcampcaptured = {
race = ['any'],
originspool = [{value = 'noble', weight = 2},{value = 'rich', weight = 5},{value = 'commoner', weight = 8},{value = 'poor', weight = 10}],
agepool = [{value = 'child', weight = 2},{value = 'teen', weight = 3}, {value = 'adult', weight = 3}],
sex = ['any'],
faction = 'stranger',
},


}


var enemypool = {
wolf = {
name = 'Wolf',
code = 'wolf',
faction = 'animal',
icon = load("res://files/images/enemies/wolf.png"),
special = null,
capture = null,
rewardpool = {bestialessenceing = 25},
rewardgold = 0,
rewardexp = 10,
stats = {health = 25, power = 5, speed = 12, energy = 50, armor = 0, magic = 0, abilities = ['attack']},
skills = [],
},
direwolf = {
name = 'Dire Wolf',
code = 'direwolf',
faction = 'animal',
icon = load("res://files/images/enemies/wolf.png"),
special = null,
capture = null,
rewardpool = {bestialessenceing = 40},
rewardgold = 0,
rewardexp = 20,
stats = {health = 50, power = 8, speed = 15, energy = 50, armor = 1, magic = 0, abilities = ['attack']},
skills = [],
},
plant = {
name = 'Plant',
code = 'plant',
faction = 'plant',
icon = load("res://files/images/enemies/plant.png"),
special = null,
capture = null,
rewardpool = {natureessenceing = 30},
rewardgold = 0,
rewardexp = 15,
stats = {health = 40, power = 5, speed = 7, energy = 50, armor = 3, magic = 0, abilities = ['attack']},
skills = [],
},
ooze = {
name = 'Ooze',
code = 'ooze',
faction = 'animal',
icon = load("res://files/images/enemies/slime.png"),
special = null,
capture = null,
rewardpool = {taintedessenceing = 25, fluidsubstanceing = 20},
rewardgold = 0,
rewardexp = 25,
stats = {health = 55, power = 7, speed = 12, energy = 50, armor = 15, magic = 0, abilities = ['attack']},
skills = [],
},
bear = {
name = 'Bear',
code = 'bear',
faction = 'animal',
icon = load("res://files/images/enemies/bear.png"),
special = null,
capture = null,
rewardpool = {bestialessenceing = 50},
rewardgold = 0,
rewardexp = 20,
stats = {health = 90, power = 7, speed = 13, energy = 50, armor = 3, magic = 0, abilities = ['attack']},
skills = [],
},
cougar = {
name = 'Cougar',
code = 'cougar',
faction = 'animal',
icon = load("res://files/images/enemies/cougar.png"),
special = null,
capture = null,
rewardpool = {bestialessenceing = 35},
rewardgold = 0,
rewardexp = 20,
stats = {health = 60, power = 6, speed = 15, energy = 50, armor = 1, magic = 0, abilities = ['attack']},
skills = [],
},
spider = {
name = 'Giant Spider',
code = 'spider',
faction = 'animal',
icon = load("res://files/images/enemies/spider.png"),
special = null,
capture = null,
rewardpool = {bestialessenceing = 75},
rewardgold = 0,
rewardexp = 50,
stats = {health = 120, power = 12, speed = 17, energy = 50, armor = 5, magic = 2, abilities = ['attack']},
skills = [],
},
peasant = {
name = 'Lone Stranger',
code = 'peasant',
faction = 'stranger',
icon = load("res://files/images/enemies/stranger.png"),
special = null,
capture = true,
capturerace = ['area'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 5},{value = 'poor', weight = 20}],
captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {gold = 15, supply = 25},
rewardgold = [1,5],
rewardexp = 15,
stats = {health = 40, power = 4, speed = 14, energy = 50, armor = 2, magic = 1, abilities = ['attack']},
skills = [],
},
elfguard = {
name = 'An Elf Warrior',
code = 'elfguard',
faction = 'elf',
icon = null,
special = null,
capture = true,
capturerace = ['area'],
captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {gold = 20, supply = 35},
rewardgold = [1,5],
rewardexp = 30,
stats = {health = 75, power = 8, speed = 15, energy = 50, armor = 3, magic = 2, abilities = ['attack']},
skills = [],
},
fairy = {
name = 'Fairy',
code = 'fairy',
faction = 'monster',
icon = null,
special = '',
capture = true,
capturerace = [['Fairy',100]],
captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 3}],
captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 2}],
capturesex = ['any'],
rewardpool = {magicessenceing = 55},
rewardgold = [5,10],
rewardexp = 20,
stats = {health = 65, power = 5, speed = 17, energy = 50, armor = 0, magic = 5, abilities = ['attack']},
skills = [],
},
harpy = {
name = 'Harpy',
code = 'harpy',
faction = 'monster',
icon = null,
special = '',
capture = true,
capturerace = [['Harpy',100]],
captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 2}],
captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 3}],
capturesex = ['any'],
rewardpool = {bestialessenceing = 35},
rewardgold = [5,10],
rewardexp = 20,
stats = {health = 75, power = 6, speed = 16, energy = 50, armor = 1, magic = 0, abilities = ['attack']},
skills = [],
},
dryad = {
name = 'Dryad',
code = 'dryad',
faction = 'monster',
icon = null,
special = '',
capture = true,
capturerace = [['Dryad',100]],
captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 1}],
captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {natureessenceing = 35},
rewardgold = [5,10],
rewardexp = 20,
stats = {health = 75, power = 6, speed = 15, energy = 50, armor = 0, magic = 0, abilities = ['attack']},
skills = [],
},
monstergirl = {
name = 'Monster ',
code = 'monstergirl',
faction = 'monster',
icon = null,
special = '',
capture = true,
capturerace = ['area'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 2}],
captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {},
rewardgold = [5,10],
rewardexp = 25,
stats = {health = 100, power = 9, speed = 17, energy = 50, armor = 2, magic = 1, abilities = ['attack']},
skills = [],
},
bandit = {
name = 'Bandit',
code = 'bandit',
faction = 'bandit',
icon = load("res://files/images/enemies/banditm.png"),
iconalt = load("res://files/images/enemies/banditf.png"),
special = '',
capture = true,
capturerace = ['bandits'],
captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 5},{value = 'slave', weight = 2}],
captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 5}],
capturesex = ['any'],
rewardpool = {gold = 35, weapondagger = 8},
rewardgold = [5,15],
rewardexp = 20,
stats = {health = 65, power = 4, speed = 16, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
skills = [],
},
banditleader = {
name = 'Bandit Leader',
code = 'banditleader',
faction = 'bandit',
icon = load("res://files/images/enemies/banditleaderm.png"),
iconalt = load("res://files/images/enemies/banditleaderf.png"),
special = '',
capture = true,
capturerace = ['bandits'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 4},{value = 'slave', weight = 1}],
captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 5}],
capturesex = ['any'],
rewardpool = {gold = 100, weaponsword = 5},
rewardgold = [30,50],
rewardexp = 50,
stats = {health = 90, power = 6, speed = 25, energy = 80, armor = 4, magic = 0, abilities = ['attack']},
skills = [],
},
marauder = {
name = 'Marauder',
code = 'marauder',
faction = 'bandit',
icon = load("res://files/images/enemies/banditleaderm.png"),
iconalt = load("res://files/images/enemies/banditleaderf.png"),
special = '',
capture = true,
capturerace = ['bandits'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 4},{value = 'slave', weight = 1}],
captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 5}],
capturesex = ['any'],
rewardpool = {gold = 65, weaponsword = 5},
rewardgold = [25,40],
rewardexp = 50,
stats = {health = 100, power = 12, speed = 30, energy = 80, armor = 4, magic = 0, abilities = ['attack']},
skills = [],
},
traveller = {
name = 'Traveller',
code = 'traveller',
faction = 'stranger',
icon = load("res://files/images/enemies/stranger.png"),
special = '',
capture = true,
capturerace = ['area'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 4},{value = 'poor', weight = 2}],
captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {gold = 50, supply = 50},
rewardgold = [5,15],
rewardexp = 20,
stats = {health = 50, power = 5, speed = 15, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
skills = [],
},
slaver = {
name = 'Slaver',
code = 'slaver',
faction = 'stranger',
icon = load("res://files/images/enemies/slaverm.png"),
iconalt = load("res://files/images/enemies/slaverf.png"),
special = null,
capture = true,
capturerace = ['bandits'],
captureoriginspool = [{value = 'slave', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 4}],
captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {gold = 35, supply = 35, armorleather = 4},
rewardgold = [5,15],
rewardexp = 25,
stats = {health = 70, power = 7, speed = 19, armor = 4, energy = 50, magic = 0, abilities = ['attack']},
skills = [],
},
wimbornpatrol = {
name = 'Wimborn Defender',
code = 'wimbornpatrol',
faction = 'stranger',
icon = null,
special = null,
capture = true,
capturerace = ['area'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 3}],
captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {gold = 20, supply = 35},
rewardgold = [1,5],
rewardexp = 25,
stats = {health = 100, power = 15, speed = 35, energy = 50, armor = 5, magic = 2, abilities = ['attack']},
skills = [],
},
frostfordpatrol = {
name = 'Frostford Defender',
code = 'frostfordpatrol',
faction = 'stranger',
icon = null,
special = null,
capture = true,
capturerace = ['area'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 3}],
captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {gold = 20, supply = 35},
rewardgold = [1,5],
rewardexp = 25,
stats = {health = 100, power = 16, speed = 33, energy = 50, armor = 5, magic = 2, abilities = ['attack']},
skills = [],
},
gornpatrol = {
name = 'Gorn Defender',
code = 'gornpatrol',
faction = 'stranger',
icon = null,
special = null,
capture = true,
capturerace = ['area'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 3}],
captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {gold = 20, supply = 35},
rewardgold = [1,5],
rewardexp = 25,
stats = {health = 120, power = 16, speed = 34, energy = 50, armor = 4, magic = 2, abilities = ['attack']},
skills = [],
},
amberguardpatrol = {
name = 'Amberguard Defender',
code = 'amberpatrol',
faction = 'stranger',
icon = null,
special = null,
capture = true,
capturerace = ['area'],
captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 3}],
captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
capturesex = ['any'],
rewardpool = {gold = 20, supply = 35},
rewardgold = [1,5],
rewardexp = 25,
stats = {health = 100, power = 16, speed = 35, energy = 50, armor = 4, magic = 2, abilities = ['attack']},
skills = [],
},



ivran = {
name = 'An Elf Leader',
code = 'ivran',
faction = 'elf',
icon = null,
special = null,
capture = true,
capturerace = ['Dark Elf',100],
captureoriginspool = [{value = 'noble', weight = 100}],
captureagepool = [{value = 'adult', weight = 100}],
capturesex = ['any'],
rewardpool = {gold = 20},
rewardgold = [5,10],
rewardexp = 50,
stats = {health = 100, power = 10, speed = 25, energy = 50, armor = 4, magic = 2, abilities = ['attack']},
skills = [],
},
ayneris = {
name = 'An Elf Leader',
code = 'ayneris',
faction = 'elf',
icon = null,
special = null,
capture = true,
capturerace = ['Elf',100],
captureoriginspool = [{value ='noble', weight = 100}],
captureagepool = [{value = 'teen', weight = 100}],
capturesex = ['female'],
rewardpool = {gold = 20},
rewardgold = [5,10],
rewardexp = 40,
stats = {health = 80, power = 12, speed = 24, energy = 50, armor = 3, magic = 3, abilities = ['attack']},
skills = [],
},
#undercity
mutant = {
name = 'Crazed mutant',
code = 'mutant',
faction = 'animal',
icon = load("res://files/images/enemies/mutant.png"),
special = null,
capture = null,
rewardpool = {taintedessenceing = 40},
rewardgold = 0,
rewardexp = 50,
stats = {health = 150, power = 15, speed = 24, energy = 50, armor = 2, magic = 2, abilities = ['attack']},
skills = [],
},
troglodyte = {
name = 'Troglodyte',
code = 'troglodyte',
faction = 'animal',
icon = load("res://files/images/enemies/troglodyte.png"),
special = null,
capture = null,
rewardpool = {taintedessenceing = 40},
rewardgold = 0,
rewardexp = 50,
stats = {health = 90, power = 12, speed = 18, energy = 50, armor = 2, magic = 2, abilities = ['attack']},
skills = [],
},
gembeetle = {
name = 'Gem Beetle',
code = 'gembeetle',
faction = 'animal',
icon = load("res://files/images/enemies/gembettle.png"),
special = null,
capture = null,
rewardpool = {gem = 50},
rewardgold = 0,
rewardexp = 10,
stats = {health = 75, power = 15, speed = 20, energy = 50, armor = 15, magic = 2, abilities = ['attack']},
skills = [],
},
bossgolem = {
name = 'Animated Golem',
code = 'bossgolem',
faction = 'boss',
icon = load("res://files/images/enemies/golem.png"),
special = null,
capture = null,
rewardpool = {gem = 50},
rewardgold = 0,
rewardexp = 10,
stats = {health = 500, power = 20, speed = 25, energy = 50, armor = 20, magic = 2, abilities = ['attack','aoeattack']},
skills = [],
},
bosswyvern = {
name = 'Cave Wyvern',
code = 'bosswyvern',
faction = 'boss',
icon = null,
special = null,
capture = null,
rewardpool = {gem = 50},
rewardgold = 0,
rewardexp = 10,
stats = {health = 450, power = 24, speed = 30, energy = 50, armor = 15, magic = 2, abilities = ['attack','aoeattack']},
skills = [],
},
}
