
extends Node

func create(code):
	if characters.has(code):
		var slave = globals.newslave(characters[code].basics[0], characters[code].basics[1],characters[code].basics[2],characters[code].basics[3])
		slave.cleartraits()
		if slave.age == 'child' && globals.rules.children == false:
			slave.age = 'teen'
		for i in characters[code]:
			if i != 'basics':
				slave[i] = characters[code][i]
		return slave
	else:
		return "Character not found: " + code


var characters = {
Emily = {
basics = ['Human', 'teen', 'female', 'poor'],
name = 'Emily',
surname = 'Hale',
titssize = 'small',
asssize = 'small',
beautybase = 33,
hairlength = 'neck',
height = 'average',
haircolor = 'brown',
eyecolor = 'gray',
hairstyle = 'straight',
vagvirgin = true,
unique = 'Emily',
tags = ['nosex'],
relatives = {father = -1, mother = 2, siblings = [], children =[]},
imageportait = "res://files/images/emily/emilyportrait.png",
obed = 80,
cour = 35,
conf = 28,
wit = 54,
charm = 41,
skin = 'pale',
},
Tisha = {
basics = ['Human', 'adult', 'female', 'commoner'],
name = 'Tisha',
surname = 'Hale',
unique = 'Tisha',
beautybase = 80,
haircolor = 'auburn',
hairlength = 'waist',
hairstyle = 'braid',
titssize = 'big',
asssize = 'average',
skin = 'fair',
eyecolor = 'gray',
vagvirgin = false,
cour = 65,
conf = 58,
wit = 39,
charm = 71,
height = 'average',
relatives = {father = -1, mother = 2, siblings = [], children =[]},
imageportait = "res://files/images/tisha/tishaportrait.png",
},
Cali = {
basics = ['Halfkin Wolf', 'child', 'female', 'commoner'],
name = 'Cali',
surname = '',
titssize = 'flat',
asssize = 'small',
beautybase = 55,
hairlength = 'shoulder',
height = 'short',
haircolor = 'gray',
eyecolor = 'blue',
eyeshape = 'slit',
hairstyle = 'straight',
skin = 'fair',
imageportait = 'res://files/images/cali/caliportrait.png',
vagvirgin = true,
obed = 65,
cour = 47,
conf = 55,
wit = 35,
charm = 20,
unique = "Cali",
},
Chloe = {
basics = ['Gnome', 'adult', 'female', 'commoner'],
name = 'Chloe',
unique = 'Chloe',
surname = '',
titssize = 'average',
asssize = 'big',
beautybase = 60,
hairlength = 'shoulder',
height = 'tiny',
haircolor = 'red',
eyecolor = 'blue',
skin = 'fair',
hairstyle = 'twintails',
vagvirgin = false,
imageportait = 'res://files/images/chloe/chloeportrait.png',
cour = 57,
conf = 34,
wit = 77,
charm = 51,
obed = 90,
},
Tia = {
basics = ['Human', 'teen', 'female', 'commoner'],
name = 'Tia',
surname = '',
beautybase = 75,
haircolor = 'brown',
hairlength = 'waist',
hairstyle = 'straight',
titssize = 'small',
asssize = 'small',
skin = 'fair',
eyecolor = 'blue',
vagvirgin = true,
cour = 23,
conf = 31,
wit = 55,
charm = 82,
height = 'short',
},
Ayneris = {
basics = ['Elf', 'teen', 'female', 'noble'],
name = 'Ayneris',
unique = 'Ayneris',
surname = '',
titssize = 'average',
asssize = 'average',
beautybase = 65,
hairlength = 'waist',
height = 'average',
haircolor = 'blond',
eyecolor = 'blue',
skin = 'fair',
hairstyle = 'straight',
vagvirgin = false,
cour = 65,
conf = 88,
wit = 51,
charm = 48,
level = 2,
sagi = 2,
sstr = 1,
skillpoints = 2,
obed = 90,
},
Yris = {
basics = ['Beastkin Cat', 'adult', 'female', 'commoner'],
name = 'Yris',
unique = 'Yris',
surname = '',
titssize = 'big',
asssize = 'average',
beautybase = 72,
hairlength = 'neck',
height = 'average',
haircolor = 'blond',
eyecolor = 'blue',
eyeshape = 'slit',
skin = 'fair',
furcolor = 'orange_white',
hairstyle = 'straight',
vagvirgin = false,
charm = 71,
wit = 62,
cour = 33,
conf = 48,
imageportait = "res://files/images/yris/yrisportrait.png",
sagi = 1,
send = 1,
loyal = 25,
obed = 90,
},
Maple = {
basics = ['Fairy', 'adult', 'female', 'rich'],
name = 'Maple',
unique = 'Maple',
surname = '',
titssize = 'average',
asssize = 'small',
beautybase = 74,
hairlength = 'shoulder',
height = 'tiny',
haircolor = 'red',
eyecolor = 'red',
skin = 'fair',
hairstyle = 'straight',
vagvirgin = false,
imageportait = 'res://files/images/maple/mapleportrait.png',
cour = 65,
conf = 73,
wit = 69,
charm = 92,
level = 5,
skillpoints = 14,
obed = 90,
traits = ['Ascetic']
},
Zoe = {
basics = ['Beastkin Wolf', 'teen', 'female', 'noble'],
name = 'Zoe',
surname = '',
beautybase = 45,
haircolor = 'brown',
hairlength = 'shoulder',
hairstyle = 'straight',
titssize = 'average',
asssize = 'average',
skin = 'fair',
eyecolor = 'red',
vagvirgin = true,
cour = 45,
conf = 55,
wit = 87,
charm = 66,
height = 'average',
furcolor = 'gray',
obed = 90,
loyal = 25,
smaf = 1,
},
}

var sprites = {
chancellor = load("res://files/images/chancellor.png"),
merchant = load("res://files/images/merchant.png"),
fairy = load("res://files/images/maple/maple.png"),
fairynaked = load("res://files/images/maple/maplenaked.png"),
melissafriendly = load("res://files/images/melissafriendly.png"),
melissaneutral = load("res://files/images/melissaneutral.png"),
melissaworried = load("res://files/images/melissaworried.png"),
emilyhappy = load("res://files/images/emily/emilyhappy.png"),
emilynormal = load("res://files/images/emily/emilynormal.png"),
emily2normal = load("res://files/images/emily/emily2neutral.png"),
emily2happy = load("res://files/images/emily/emily2happy.png"),
emily2worried = load("res://files/images/emily/emily2worried.png"),
emilynakedhappy = load("res://files/images/emily/emilynakedhappy.png"),
emilynakedneutral = load("res://files/images/emily/emilynakedneutral.png"),
calineutral = load("res://files/images/cali/calineutral.png"),
calihappy = load("res://files/images/cali/calihappy.png"),
calinakedhappy = load("res://files/images/cali/calinakedneutral.png"),
calinakedangry = load("res://files/images/cali/calinakedangry.png"),
caliangry = load("res://files/images/cali/caliangry.png"),
caliangry2 = load("res://files/images/cali/caliangry2.png"),
sebastian = load("res://files/images/sebastian.png"),
tishahappy = load("res://files/images/tisha/tishahappy.png"),
tishaneutral = load("res://files/images/tisha/tishaneutral.png"),
tishaangry = load("res://files/images/tisha/tishaangry.png"),
tishashocked = load("res://files/images/tisha/tishashocked.png"),
tishanakedhappy = load("res://files/images/tisha/tishanakedhappy.png"),
tishanakedneutral = load("res://files/images/tisha/tishanakedneutral.png"),
chloehappy = load("res://files/images/chloe/chloehappy.png"),
chloenakedhappy = load("res://files/images/chloe/chloenakedhappy.png"),
chloeneutral = load("res://files/images/chloe/chloeneutral.png"),
chloenakedneutral = load("res://files/images/chloe/chloenakedneutral.png"),
chloehappy2 = load("res://files/images/chloe/chloehappy2.png"),
chloeshy2 = load("res://files/images/chloe/chloeshy2.png"),
chloenakedshy = load("res://files/images/chloe/chloenakedshy.png"),
chloeneutral2 = load("res://files/images/chloe/chloeneutral2.png"),
aydanormal = load("res://files/images/aydanormal.png"),
aydanormal2 = load("res://files/images/aydanormal2.png"),
yrisnormal = load("res://files/images/yris/yrisnormaldressed.png"),
yrisalt = load("res://files/images/yris/yrisaltdressed.png"),
yrisshock = load("res://files/images/yris/yrisshockdressed.png"),
yrisnormalnaked = load("res://files/images/yris/yrisnormalnaked.png"),
yrisaltnaked = load("res://files/images/yris/yrisaltnaked.png"),
yrisshocknaked = load("res://files/images/yris/yrisshocknaked.png"),
}
